#####################################################################
# Data CI Pipeline
# https://aka.ms/yaml
#####################################################################

trigger:
  branches:
    include:
    - master
    - release
    - develop
  paths:
    #include: 
    #- Source/
    exclude: 
    - README.md
    - images/*
    - Build/*

resources:
  repositories:
  - repository: templates
    type: git
    name: BuildTemplates/BuildTemplates

parameters:
  - name: SkipTest
    type: boolean
    default: false

variables:
  - template: .build/VarsPackage.yml
  - template: .build/VarsBuild.yml 
  - name:  BuildSolution
    value: '**/DigitalResults.sln'
  - name:  PackageArtifactPath
    value: $(Build.ArtifactStagingDirectory)\nuget
  - name:  SigningCertName
    value: 'Digital Caesar LLC.snk'
  - name: ArtifactName
    value: nuget
  - name:  UnitTestProjects
    value: '**/Tests/**/*UnitTests.csproj'
  - name:  IntegrationTestProjects
    value: '**/Tests/**/*IntegrationTests.csproj'
  - ${{ if eq(variables['build.SourceBranchName'], 'develop') }}:
    - name:  BuildConfiguration
      value: 'Debug'
    - name: BuildPlatform
      value:  'X86'
    - name:  BuildVersionSuffix
      value: '-alpha'    
    - name:  PackagePublish
      value: false
  - ${{ if eq(variables['build.SourceBranchName'], 'release') }}:
    - name:  BuildConfiguration
      value: 'Release'
    - name: BuildPlatform
      value:  'Any CPU'
    - name: BuildVersionSuffix
      value: '-rc'
    - name:  PackagePublish
      value: true
  - ${{ if eq(variables['build.SourceBranchName'], 'master') }}:
    - name:  BuildConfiguration
      value: 'Release'
    - name: BuildPlatform
      value:  'Any CPU'
    - name: BuildVersionSuffix
      value: ''
    - name:  PackagePublish
      value: true
  
name: $(date:yyyyMMdd)$(rev:.r)

jobs:
- job: Main
  displayName: Test, Build, and Publish
  workspace:
    clean: all
  timeoutInMinutes: 20
  pool: 
    name: default
    demands: agent.os -equals Windows_NT
  steps:    
  # Setup Tools
  - template: Package/JobSetup.yml@templates
    parameters:
      NetCoreSdkVersion: $(NetCoreSdkVersion)
      NetCoreRunVersion: $(NetCoreRunVersion)
      NugetVersion:      $(NugetVersion)
      BuildSolution:     $(BuildSolution)
      Restore: true
      UseMaui: false        
  # Get Signing Certificate
  # Signature required for test package in Release mode.  Disable by running in Debug/Mock, or otherwise amend project to ignore signature file unless provided.  
  - ${{ if or(eq(variables['Build.SourceBranch'], 'refs/heads/master'),eq(variables['Build.SourceBranch'], 'refs/heads/release')) }}:
    - template:  Package/JobSigning.yml@templates
      parameters: 
        CertificateName: 'Digital Caesar LLC.snk'
  # Run Test
  - ${{ if eq(parameters.SkipTest, false) }}:
    - template: Package/JobTest.yml@templates
      parameters: 
        BuildConfiguration:      $(BuildConfiguration)
        UnitTestProjects:        $(UnitTestProjects)
        IntegrationTestProjects: $(IntegrationTestProjects)
 
  - template: Package/BuildWindows.yml@templates
    parameters: 
      BuildConfiguration:   $(BuildConfiguration)
      BuildPlatform:        $(BuildPlatform)
      PackagePath:          $(PackageArtifactPath)
      PackageVersionSuffix: $(BuildVersionSuffix)
      ArtifactName:         $(ArtifactName)
      BuildSolution:        $(BuildSolution)
      PackageVersionNumber: $(VersionNumber)
      BuildVersionNumber:   $(Build.BuildId)
      PublishMode:          ${{ variables.PackagePublish }}  
